name: countcolor
channels:
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - pip
  - numpy
  - pandas
  
  - requests
  - lxml
  - beautifulsoup4
  - matplotlib
  - seaborn

  - ipywidgets
  - ipython





